export const enum Z64LibEvents{
    ADULT_MODEL_PRELOAD = "ADULT_MODEL_PRELOAD",
    ADULT_MODEL_POSTLOAD = "ADULT_MODEL_POSTLOAD",
    CHILD_MODEL_PRELOAD = "CHILD_MODEL_PRELOAD",
    CHILD_MODEL_POSTLOAD = "CHILD_MODEL_POSTLOAD",
    ZORA_MODEL_PRELOAD = "ZORA_MODEL_PRELOAD",
    ZORA_MODEL_POSTLOAD = "ZORA_MODEL_POSTLOAD",
    ANIM_FILE_PRELOAD = "ANIM_FILE_PRELOAD",
    ANIM_FILE_POSTLOAD = "ANIM_FILE_POSTLOAD"
}