export const LUT_Map: Map<string, number> = new Map<string, number>();
LUT_Map.set("LUT_DL_WAIST", 0x5090);
LUT_Map.set("LUT_DL_RTHIGH", 0x5098);
LUT_Map.set("LUT_DL_RSHIN", 0x50A0);
LUT_Map.set("LUT_DL_RFOOT", 0x50A8);
LUT_Map.set("LUT_DL_LTHIGH", 0x50B0);
LUT_Map.set("LUT_DL_LSHIN", 0x50B8);
LUT_Map.set("LUT_DL_LFOOT", 0x50C0);
LUT_Map.set("LUT_DL_HEAD", 0x50C8);
LUT_Map.set("LUT_DL_HAT", 0x50D0);
LUT_Map.set("LUT_DL_COLLAR", 0x50D8);
LUT_Map.set("LUT_DL_LSHOULDER", 0x50E0);
LUT_Map.set("LUT_DL_LFOREARM", 0x50E8);
LUT_Map.set("LUT_DL_RSHOULDER", 0x50F0);
LUT_Map.set("LUT_DL_RFOREARM", 0x50F8);
LUT_Map.set("LUT_DL_TORSO", 0x5100);
LUT_Map.set("LUT_DL_LHAND", 0x5108);
LUT_Map.set("LUT_DL_LFIST", 0x5110);
LUT_Map.set("LUT_DL_LHAND_BOTTLE", 0x5118);
LUT_Map.set("LUT_DL_RHAND", 0x5120);
LUT_Map.set("LUT_DL_RFIST", 0x5128);
LUT_Map.set("LUT_DL_SWORD_SHEATH", 0x5130);
LUT_Map.set("LUT_DL_SWORD_HILT", 0x5138);
LUT_Map.set("LUT_DL_SWORD_BLADE", 0x5140);
LUT_Map.set("LUT_DL_LONGSWORD_HILT", 0x5148);
LUT_Map.set("LUT_DL_LONGSWORD_BLADE", 0x5150);
LUT_Map.set("LUT_DL_LONGSWORD_BROKEN", 0x5158);
LUT_Map.set("LUT_DL_SHIELD_HYLIAN", 0x5160);
LUT_Map.set("LUT_DL_SHIELD_MIRROR", 0x5168);
LUT_Map.set("LUT_DL_HAMMER", 0x5170);
LUT_Map.set("LUT_DL_BOTTLE", 0x5178);
LUT_Map.set("LUT_DL_BOW", 0x5180);
LUT_Map.set("LUT_DL_OCARINA_TIME", 0x5188);
LUT_Map.set("LUT_DL_HOOKSHOT", 0x5190);
LUT_Map.set("LUT_DL_UPGRADE_LFOREARM", 0x5198);
LUT_Map.set("LUT_DL_UPGRADE_LHAND", 0x51A0);
LUT_Map.set("LUT_DL_UPGRADE_LFIST", 0x51A8);
LUT_Map.set("LUT_DL_UPGRADE_RFOREARM", 0x51B0);
LUT_Map.set("LUT_DL_UPGRADE_RHAND", 0x51B8);
LUT_Map.set("LUT_DL_UPGRADE_RFIST", 0x51C0);
LUT_Map.set("LUT_DL_BOOT_LIRON", 0x51C8);
LUT_Map.set("LUT_DL_BOOT_RIRON", 0x51D0);
LUT_Map.set("LUT_DL_BOOT_LHOVER", 0x51D8);
LUT_Map.set("LUT_DL_BOOT_RHOVER", 0x51E0);
LUT_Map.set("LUT_DL_FPS_LFOREARM", 0x51E8);
LUT_Map.set("LUT_DL_FPS_LHAND", 0x51F0);
LUT_Map.set("LUT_DL_FPS_RFOREARM", 0x51F8);
LUT_Map.set("LUT_DL_FPS_RHAND", 0x5200);
LUT_Map.set("LUT_DL_FPS_HOOKSHOT", 0x5208);
LUT_Map.set("LUT_DL_HOOKSHOT_CHAIN", 0x5210);
LUT_Map.set("LUT_DL_HOOKSHOT_HOOK", 0x5218);
LUT_Map.set("LUT_DL_HOOKSHOT_AIM", 0x5220);
LUT_Map.set("LUT_DL_BOW_STRING", 0x5228);
LUT_Map.set("LUT_DL_BLADEBREAK", 0x5230);
LUT_Map.set("LUT_DL_SWORD_SHEATHED", 0x5238);
LUT_Map.set("LUT_DL_SHIELD_HYLIAN_BACK", 0x5258);
LUT_Map.set("LUT_DL_SHIELD_MIRROR_BACK", 0x5268);
LUT_Map.set("LUT_DL_SWORD_SHIELD_HYLIAN", 0x5278);
LUT_Map.set("LUT_DL_SWORD_SHIELD_MIRROR", 0x5288);
LUT_Map.set("LUT_DL_SHEATH0_HYLIAN", 0x5298);
LUT_Map.set("LUT_DL_SHEATH0_MIRROR", 0x52A8);
LUT_Map.set("LUT_DL_LFIST_SWORD", 0x52B8);
LUT_Map.set("LUT_DL_LFIST_LONGSWORD", 0x52D0);
LUT_Map.set("LUT_DL_LFIST_LONGSWORD_BROKEN", 0x52E8);
LUT_Map.set("LUT_DL_LFIST_HAMMER", 0x5300);
LUT_Map.set("LUT_DL_RFIST_SHIELD_HYLIAN", 0x5310);
LUT_Map.set("LUT_DL_RFIST_SHIELD_MIRROR", 0x5320);
LUT_Map.set("LUT_DL_RFIST_BOW", 0x5330);
LUT_Map.set("LUT_DL_RFIST_HOOKSHOT", 0x5340);
LUT_Map.set("LUT_DL_RHAND_OCARINA_TIME", 0x5350);
LUT_Map.set("LUT_DL_FPS_RHAND_BOW", 0x5360);
LUT_Map.set("LUT_DL_FPS_LHAND_HOOKSHOT", 0x5370);

export const Manifest_Map: Map<string, number> = new Map<string, number>();
Manifest_Map.set("Sheath", 0x19);
Manifest_Map.set("FPS.Hookshot", 0x2A);
Manifest_Map.set("Hilt.2", 0x35);
Manifest_Map.set("Blade.2", 0x41);
Manifest_Map.set("Hookshot.Spike", 0x54);
Manifest_Map.set("Hookshot", 0x61);
Manifest_Map.set("Fist.L", 0x6C);
Manifest_Map.set("Fist.R", 0x77);
Manifest_Map.set("FPS.Forearm.L", 0x89);
Manifest_Map.set("FPS.Forearm.R", 0x9B);
Manifest_Map.set("Gauntlet.Fist.L", 0xAF);
Manifest_Map.set("Gauntlet.Fist.R", 0xC3);
Manifest_Map.set("Gauntlet.Forearm.L", 0xDA);
Manifest_Map.set("Gauntlet.Forearm.R", 0xF1);
Manifest_Map.set("Gauntlet.Hand.L", 0x105);
Manifest_Map.set("Gauntlet.Hand.R", 0x119);
Manifest_Map.set("Bottle.Hand.L", 0x12B);
Manifest_Map.set("FPS.Hand.L", 0x13A);
Manifest_Map.set("FPS.Hand.R", 0x149);
Manifest_Map.set("Bow.String", 0x158);
Manifest_Map.set("Bow", 0x160);
Manifest_Map.set("Blade.3.Break", 0x172);
Manifest_Map.set("Blade.3", 0x17E);
Manifest_Map.set("Bottle", 0x189);
Manifest_Map.set("Broken.Blade.3", 0x19C);
Manifest_Map.set("Foot.2.L", 0x1A9);
Manifest_Map.set("Foot.2.R", 0x1B6);
Manifest_Map.set("Foot.3.L", 0x1C3);
Manifest_Map.set("Foot.3.R", 0x1D0);
Manifest_Map.set("Hammer", 0x1DB);
Manifest_Map.set("Hilt.3", 0x1E6);
Manifest_Map.set("Hookshot.Aiming.Reticule", 0x203);
Manifest_Map.set("Hookshot.Chain", 0x216);
Manifest_Map.set("Ocarina.2", 0x224);
Manifest_Map.set("Shield.2", 0x231);
Manifest_Map.set("Shield.3", 0x23E);
Manifest_Map.set("Limb 1", 0x249);
Manifest_Map.set("Limb 3", 0x254);
Manifest_Map.set("Limb 4", 0x25F);
Manifest_Map.set("Limb 5", 0x26A);
Manifest_Map.set("Limb 6", 0x275);
Manifest_Map.set("Limb 7", 0x280);
Manifest_Map.set("Limb 8", 0x28B);
Manifest_Map.set("Limb 10", 0x297);
Manifest_Map.set("Limb 11", 0x2A3);
Manifest_Map.set("Limb 12", 0x2AF);
Manifest_Map.set("Limb 13", 0x2BB);
Manifest_Map.set("Limb 14", 0x2C7);
Manifest_Map.set("Limb 15", 0x2D3);
Manifest_Map.set("Limb 16", 0x2DF);
Manifest_Map.set("Limb 17", 0x2EB);
Manifest_Map.set("Limb 18", 0x2F7);
Manifest_Map.set("Limb 20", 0x303);

export const LM: Map<string, string> = new Map<string, string>();
LM.set("LUT_DL_WAIST", "Limb 1");
LM.set("LUT_DL_RTHIGH", "Limb 3");
LM.set("LUT_DL_RSHIN", "Limb 4");
LM.set("LUT_DL_RFOOT", "Limb 5");
LM.set("LUT_DL_LTHIGH", "Limb 6");
LM.set("LUT_DL_LSHIN", "Limb 7");
LM.set("LUT_DL_LFOOT", "Limb 8");
LM.set("LUT_DL_HEAD", "Limb 10");
LM.set("LUT_DL_HAT", "Limb 11");
LM.set("LUT_DL_COLLAR", "Limb 12");
LM.set("LUT_DL_LSHOULDER", "Limb 13");
LM.set("LUT_DL_LFOREARM", "Limb 14");
LM.set("LUT_DL_RSHOULDER", "Limb 16");
LM.set("LUT_DL_RFOREARM", "Limb 17");
LM.set("LUT_DL_TORSO", "Limb 20");
LM.set("LUT_DL_LHAND", "Limb 15");
LM.set("LUT_DL_LFIST", "Fist.L");
LM.set("LUT_DL_LHAND_BOTTLE", "Bottle.Hand.L");
LM.set("LUT_DL_RHAND", "Limb 18");
LM.set("LUT_DL_RFIST", "Fist.R");
LM.set("LUT_DL_SWORD_SHEATH", "Sheath");
LM.set("LUT_DL_SWORD_HILT", "Hilt.2");
LM.set("LUT_DL_SWORD_BLADE", "Blade.2");
LM.set("LUT_DL_LONGSWORD_HILT", "Hilt.3");
LM.set("LUT_DL_LONGSWORD_BLADE", "Blade.3");
LM.set("LUT_DL_LONGSWORD_BROKEN", "Broken.Blade.3");
LM.set("LUT_DL_SHIELD_HYLIAN", "Shield.2");
LM.set("LUT_DL_SHIELD_MIRROR", "Shield.3");
LM.set("LUT_DL_HAMMER", "Hammer");
LM.set("LUT_DL_BOTTLE", "Bottle");
LM.set("LUT_DL_BOW", "Bow");
LM.set("LUT_DL_OCARINA_TIME", "Ocarina.2");
LM.set("LUT_DL_HOOKSHOT", "Hookshot");
LM.set("LUT_DL_UPGRADE_LFOREARM", "Gauntlet.Forearm.L");
LM.set("LUT_DL_UPGRADE_LHAND", "Gauntlet.Hand.L");
LM.set("LUT_DL_UPGRADE_LFIST", "Gauntlet.Fist.L");
LM.set("LUT_DL_UPGRADE_RFOREARM", "Gauntlet.Forearm.R");
LM.set("LUT_DL_UPGRADE_RHAND", "Gauntlet.Hand.R");
LM.set("LUT_DL_UPGRADE_RFIST", "Gauntlet.Fist.R");
LM.set("LUT_DL_BOOT_LIRON", "Foot.2.L");
LM.set("LUT_DL_BOOT_RIRON", "Foot.2.R");
LM.set("LUT_DL_BOOT_LHOVER", "Foot.3.L");
LM.set("LUT_DL_BOOT_RHOVER", "Foot.3.R");
LM.set("LUT_DL_FPS_LFOREARM", "FPS.Forearm.L");
LM.set("LUT_DL_FPS_LHAND", "FPS.Hand.L");
LM.set("LUT_DL_FPS_RFOREARM", "FPS.Forearm.R");
LM.set("LUT_DL_FPS_RHAND", "FPS.Hand.R");
LM.set("LUT_DL_FPS_HOOKSHOT", "FPS.Hookshot");
LM.set("LUT_DL_HOOKSHOT_CHAIN", "Hookshot.Chain");
LM.set("LUT_DL_HOOKSHOT_HOOK", "Hookshot.Spike");
LM.set("LUT_DL_HOOKSHOT_AIM", "Hookshot.Aiming.Reticule");
LM.set("LUT_DL_BOW_STRING", "Bow.String");
LM.set("LUT_DL_BLADEBREAK", "Blade.3.Break");